In [70]:
import pandas as pd
data=pd.read_csv('titanic.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [71]:
#Work on a copy
df=data.copy()

In [72]:
#exploring data
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

age, cabin and embarked have missing values

In [74]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Only 38% survived

In [75]:
#check on missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [76]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

Check the validity of the data type of each column by comparing the unique values of each column with its data type:-

In [77]:
unique_type=pd.DataFrame({
    'column':df.columns,
    'unique_values': [df[col].unique() for col in df.columns],
    'type': [df[col].dtype for col in df.columns]
})
unique_type

         column                                      unique_values     type
0   PassengerId  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...    int64
1      Survived                                             [0, 1]    int64
2        Pclass                                          [3, 1, 2]    int64
3          Name  [Braund, Mr. Owen Harris, Cumings, Mrs. John B...      str
4           Sex                                     [male, female]      str
5           Age  [22.0, 38.0, 26.0, 35.0, nan, 54.0, 2.0, 27.0,...  float64
6         SibSp                              [1, 0, 3, 4, 2, 5, 8]    int64
7         Parch                              [0, 1, 2, 5, 3, 4, 6]    int64
8        Ticket  [A/5 21171, PC 17599, STON/O2. 3101282, 113803...      str
9          Fare  [7.25, 71.2833, 7.925, 53.1, 8.05, 8.4583, 51....  float64
10        Cabin  [nan, C85, C123, E46, G6, C103, D56, A6, C23 C...      str
11     Embarked                                     [S, C, Q, nan]      str


1. Pclass should be category (1st,snd,3rd)
2. Sex should be category
3. Embarked should be category

Start cleaning data:-

1. Correct data types:

In [78]:

df['Pclass']=df['Pclass'].astype('category')
df['Pclass']= df['Pclass'].cat.rename_categories({1:'1st',2:'2nd',3:'3rd'})
df['Sex']=df['Sex'].astype('category')
df['Embarked']=df['Embarked'].astype('category')
#check after adjusting:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    category
 3   Name         891 non-null    str
 4   Sex          891 non-null    category
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    category
dtypes: category(3), float64(2), int64(4), str(3)
memory usage: 65.5 KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3rd,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1st,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3rd,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1st,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3rd,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Round up age values:

In [79]:
df['Age']= df['Age'].round(2)
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

3. check for duplicates:

In [80]:
df.duplicated().sum

<bound method Series.sum of 0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool>

4. filling the two missed embarked values with the most frequent value (mfv)

In [81]:
mfv=df['Embarked'].mode()[0]
df['Embarked'].fillna(mfv,inplace=True)

C:\Users\rofai\AppData\Local\Temp\ipykernel_8628\1493075473.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Embarked'].fillna(mfv,inplace=True)

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: category
Categories (3, str): ['C', 'Q', 'S']

Working on Age:
1- Understanding the data and its defects

In [82]:
age_stats = df.groupby('Pclass')['Age'].agg(['min', 'max', 'mean', 'median', 'count', 'size'])
age_stats

         min   max       mean  median  count  size
Pclass
1st     0.92  80.0  38.233441    37.0    186   216
2nd     0.67  70.0  29.877630    29.0    173   184
3rd     0.42  74.0  25.140620    24.0    355   491

In [83]:
age_stats['range']=age_stats['max']-age_stats['min']
age_stats

         min   max       mean  median  count  size  range
Pclass
1st     0.92  80.0  38.233441    37.0    186   216  79.08
2nd     0.67  70.0  29.877630    29.0    173   184  69.33
3rd     0.42  74.0  25.140620    24.0    355   491  73.58

In [84]:
#calculating total missing ages
total_missing_ages =df['Age'].isna().sum()
total_missing_ages

np.int64(177)

In [85]:
#calculate total missing Ages (tma) for each class of passengers
tma=df.groupby('Pclass')['Age'].apply(lambda x: x.isna().sum())
tma
#calculate the percentage of missing ages for each
total_age_by_class=df.groupby(['Pclass'])['Age'].size()
total_age_by_class
tma_percentage= (tma/total_age_by_class)*100
tma_percentage

Pclass
1st    13.888889
2nd     5.978261
3rd    27.698574
Name: Age, dtype: float64

5. Filling the missing ages by the mean value of ages in each class:-

In [86]:
df['Age']=df.groupby('Pclass')['Age'].transform(lambda x: x.fillna(x.mean()))
df['Age']

0      22.00000
1      38.00000
2      26.00000
3      35.00000
4      35.00000
         ...
886    27.00000
887    19.00000
888    25.14062
889    26.00000
890    32.00000
Name: Age, Length: 891, dtype: float64

All age entries are filled

* Exploratory Data Analysis (EDA)
* understanding the relation between survival rates and other factors.

In [98]:
total_survived=df['Survived'].sum()
percentage=(total_survived/df['Survived'].count())*100
percentage

np.float64(38.38383838383838)

1. Understanding cabin and class factors:

In [95]:
# Extract deck letter
def extract_deck(cabin):
    if pd.notna(cabin):
        cabin_str=str(cabin).strip()
        deck=cabin_str[0]
        if deck in ['A', 'B', 'C', 'D', 'E', 'F', 'G']:
            return deck
        else:
            return 'nonfamiliar deck'
    else:
        return 'missing'
df['Deck']=df['Cabin'].apply(extract_deck)
#group deck and class
deck_class=pd.crosstab(df['Pclass'],df['Deck'])
deck_class

Deck     A   B   C   D   E  F  G  missing  nonfamiliar deck
Pclass
1st     15  47  59  29  25  0  0       40                 1
2nd      0   0   0   4   4  8  0      168                 0
3rd      0   0   0   0   3  5  4      479                 0

In [97]:
deck_class_survival = df.groupby(['Deck', 'Pclass'])['Survived'].mean() * 100
print("\n=== Survival Rate by Deck AND Passenger Class ===")
print(deck_class_survival.sort_values(ascending=False))

=== Survival Rate by Deck AND Passenger Class ===
Deck              Pclass
E                 3rd       100.000000
F                 2nd        87.500000
D                 1st        75.862069
                  2nd        75.000000
E                 2nd        75.000000
B                 1st        74.468085
E                 1st        72.000000
C                 1st        59.322034
G                 3rd        50.000000
missing           1st        47.500000
A                 1st        46.666667
missing           2nd        44.047619
                  3rd        23.590814
F                 3rd        20.000000
nonfamiliar deck  1st         0.000000
Name: Survived, dtype: float64

2. Understanding gender factor:

In [103]:
sex_survival = df.groupby('Sex')['Survived'].mean() * 100
sex_survival

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

Females had ~74% survival, males only ~19%.

3. Understanding age factor:

In [110]:
def age_group(Age):
     if 12 >= Age:
        return "Child (0-12)"
     elif 18 >= Age:
        return "Teen (13-18)"
     elif 50 >= Age:
        return "Adult (19-50)"
     else:
        return 'Senior (51+)'

df['Age_group'] = df['Age'].apply(age_group)
age_survival = df.groupby('Age_group')['Survived'].mean() * 100
print(age_survival)

Age_group
Adult (19-50)    36.337209
Child (0-12)     57.971014
Senior (51+)     34.375000
Teen (13-18)     42.857143
Name: Survived, dtype: float64

4. Understanding family size factor:

In [109]:
# Calculate family size
df['Family_size'] = df['SibSp'] + df['Parch']

# categorize family size
def family_category(size):
    if size == 0:
        return 'Alone'
    elif size <= 3:
        return 'Small Family (1-3)'
    else:
        return 'Large Family (4+)'

df['Family_category'] = df['Family_size'].apply(family_category)
family_survival = df.groupby('Family_category')['Survived'].mean() * 100
family_survival

Family_category
Alone                 30.353818
Large Family (4+)     16.129032
Small Family (1-3)    57.876712
Name: Survived, dtype: float64

5. Understanding embarked facor

In [111]:
emb_survival = df.groupby('Embarked')['Survived'].mean() * 100
emb_survival

Embarked
C    55.357143
Q    38.961039
S    33.695652
Name: Survived, dtype: float64